spring:
  application:
    name: gateway
  cloud:        # spring cloud gateway 路由配置方式
    gateway:
      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
      routes:
      - id: 163                     #网关路由到网易官网
        uri: http://www.163.com/
        predicates:
          - Path=/163/**
      - id:  CLIENT          #网关路由到订单CLIENT
        uri: lb://CLIENT
        predicates:
         - Path=/service/**
      - id:  demo          #网关路由到SERVICE
        uri: lb://SERVICE
        predicates:
         - Path=/demo/**
        filters:
        - StripPrefix=1

server:
  port: 8086


logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    
hystrix.command.default.execution.timeout.enabled: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 90000
